#!/bin/bash
# Weekly Token Audit Report
# Generates a comprehensive token status report every Sunday 19:00
# Run: ./token-audit-report.sh

set -euo pipefail

STATE_FILE="$HOME/.openclaw/workspace/memory/tokens.json"
REPORT_FILE="$HOME/.openclaw/workspace/memory/token-audit-$(date +%Y-W%V).md"
LOG_FILE="$HOME/.openclaw/logs/token-audit.log"

mkdir -p "$(dirname "$REPORT_FILE")" "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "Starting weekly token audit..."

# Generate markdown report
cat > "$REPORT_FILE" << EOF
# Token Audit Report
**Generated:** $(date)
**Week:** $(date +%Y-W%V)

## Executive Summary

| Service | Status | Days Until Expiry | Action Required |
|---------|--------|-------------------|-----------------|
EOF

# Parse tokens.json and generate table
if [[ -f "$STATE_FILE" ]]; then
    jq -r '.tokens | to_entries[] | "\(.key) | \(.value.status) | \(.value.days_until_expiry // "∞") | \(.value.notes)"' "$STATE_FILE" | while read -r line; do
        key=$(echo "$line" | cut -d'|' -f1 | xargs)
        status=$(echo "$line" | cut -d'|' -f2 | xargs)
        days=$(echo "$line" | cut -d'|' -f3 | xargs)
        notes=$(echo "$line" | cut -d'|' -f4 | xargs)
        
        # Determine action
        action="None"
        if [[ "$days" != "∞" && "$days" != "null" ]] && [[ ${days:-999} -lt 7 ]]; then
            action="⚠️ Review soon"
        fi
        if [[ ${days:-999} -lt 2 ]]; then
            action="🔴 URGENT - Take action now"
        fi
        
        echo "| $key | $status | $days | $action |" >> "$REPORT_FILE"
    done
else
    echo "| N/A | ERROR | - | tokens.json not found |" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << 'EOF'

## Detailed Status

### Auto-Refreshing Tokens

#### Withings (Health API)
- **Status:** ✅ Functional
- **Last Refreshed:** Daily via cron (08:00 CET)
- **Expiry:** ~2 years (very stable)
- **Action:** None required

#### Instagram (Meta Graph API)
- **Status:** ✅ Valid
- **Expiry:** 60 days
- **Refresh:** Automatic if < 7 days until expiry
- **Action:** Monitor for alerts

#### Google OAuth (Gmail, Calendar)
- **Status:** ✅ Managed by gog CLI
- **Expiry:** Automatic refresh on use
- **Action:** None required

### Manual Refresh Tokens

#### WhatsApp Business
- **Status:** ⚠️ Manual only
- **Expiry:** 14 days
- **Alert:** 2 days before expiry
- **Action:** When prompted, run: `openclaw channels login whatsapp`

## Cron Schedule

| Task | Frequency | Time (CET) | Status |
|------|-----------|-----------|--------|
| Token Refresh | Daily | 08:00 | ✅ Active |
| Health Check | Daily | 09:00 | ✅ Active |
| Token Audit | Weekly | Sunday 19:00 | ✅ Active |

## Alerts Configuration

### WhatsApp Expiry
- **Trigger:** < 2 days until expiry
- **Channel:** Telegram Topic 125
- **Message:** "⚠️ WhatsApp session expires in X days. Run: openclaw channels login whatsapp"

### Instagram Expiry
- **Trigger:** < 7 days until expiry
- **Channel:** Telegram Topic 125
- **Message:** "⚠️ Instagram token expires in X days. Auto-refresh will attempt."

## Recovery Procedures

### WhatsApp Token Expired
```bash
openclaw channels login whatsapp
# Scan QR code with your phone
# Reconnect to start new 14-day session
```

### Instagram Token Needs Manual Refresh
If auto-refresh fails:
```bash
# Get new token from Meta Graph Explorer or dashboard
# Update .env:
sed -i '' 's/META_ACCESS_TOKEN=.*/META_ACCESS_TOKEN=<new_token>/' ~/.openclaw/.env
openclaw gateway restart
```

### Google OAuth Broken
```bash
gog auth refresh
# Or delete credentials and re-authenticate:
rm ~/Library/Application\ Support/gogcli/credentials.json
gog auth init
```

## Next Review
**Date:** $(date -d "1 week" +%Y-%m-%d 2>/dev/null || date -v+7d +%Y-%m-%d)

---

*Report generated by: token-audit-report.sh*
*Location: memory/token-audit-YYYY-Www.md*
EOF

log "✅ Audit report generated: $REPORT_FILE"

# Send summary to Telegram if there are issues
ALERT_COUNT=$(grep -c "🔴\|⚠️" "$REPORT_FILE" || true)
if [[ $ALERT_COUNT -gt 0 ]]; then
    log "⚠️  Found $ALERT_COUNT alerts in audit"
    # Optional: Send to Telegram Topic 125 (can be enabled if message tool is available)
    # openclaw message send --channel telegram --topic 125 --message "📋 Weekly Token Audit Complete. $ALERT_COUNT alert(s) found. Check memory/token-audit-$(date +%Y-W%V).md"
else
    log "✅ No critical alerts in this week's audit"
fi

exit 0
